#############################################################################
# Makefile for building: Anime-Batle.app/Contents/MacOS/Anime-Batle
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Anime-Batle.pro
# Template: app
# Command: /Users/silarbinunzio/Qt/5.15.2/clang_64/bin/qmake -o Makefile Anime-Batle.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers -I../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I../Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.15.2/clang_64/mkspecs/macx-clang -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib
QMAKE         = /Users/silarbinunzio/Qt/5.15.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/silarbinunzio/Qt/5.15.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/silarbinunzio/Qt/5.15.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Anime-Batle1.0.0
DISTDIR = /Users/silarbinunzio/Anime-Batle/.tmp/Anime-Batle1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/silarbinunzio/Qt/5.15.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib -framework QtWidgets -framework QtMultimedia -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = character_select.cpp \
		main.cpp \
		animebattle.cpp \
		param.cpp \
		presets.cpp qrc_AnimeBattle.cpp \
		moc_animebattle.cpp \
		moc_character_select.cpp \
		moc_param.cpp \
		moc_presets.cpp
OBJECTS       = character_select.o \
		main.o \
		animebattle.o \
		param.o \
		presets.o \
		qrc_AnimeBattle.o \
		moc_animebattle.o \
		moc_character_select.o \
		moc_param.o \
		moc_presets.o
DIST          = TitleBG.png \
		../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		Anime-Batle.pro animebattle.h \
		character_select.h \
		param.h \
		presets.h character_select.cpp \
		main.cpp \
		animebattle.cpp \
		param.cpp \
		presets.cpp
QMAKE_TARGET  = Anime-Batle
DESTDIR       = 
TARGET        = Anime-Batle.app/Contents/MacOS/Anime-Batle

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/silarbinunzio/Anime-Batle/Anime-Batle.pro


include /Users/silarbinunzio/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Anime-Batle.app/Contents/MacOS/Anime-Batle: ui_animebattle.h ui_character_select.h ui_param.h ui_presets.h $(OBJECTS)  
	@test -d Anime-Batle.app/Contents/MacOS/ || mkdir -p Anime-Batle.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Anime-Batle.pro ../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		Anime-Batle.pro \
		AnimeBattle.qrc \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Resources/QtMultimedia.prl \
		../Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../Qt/5.15.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Anime-Batle.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.15.2/clang_64/mkspecs/qdevice.pri:
../Qt/5.15.2/clang_64/mkspecs/features/device_config.prf:
../Qt/5.15.2/clang_64/mkspecs/common/unix.conf:
../Qt/5.15.2/clang_64/mkspecs/common/mac.conf:
../Qt/5.15.2/clang_64/mkspecs/common/macx.conf:
../Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.15.2/clang_64/mkspecs/common/clang.conf:
../Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.15.2/clang_64/mkspecs/qconfig.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttracker_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.15.2/clang_64/mkspecs/features/default_post.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf:
../Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.15.2/clang_64/mkspecs/features/qt.prf:
../Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf:
../Qt/5.15.2/clang_64/mkspecs/features/resources.prf:
../Qt/5.15.2/clang_64/mkspecs/features/moc.prf:
../Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.15.2/clang_64/mkspecs/features/uic.prf:
../Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf:
../Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.15.2/clang_64/mkspecs/features/yacc.prf:
../Qt/5.15.2/clang_64/mkspecs/features/lex.prf:
Anime-Batle.pro:
AnimeBattle.qrc:
../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Resources/QtMultimedia.prl:
../Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../Qt/5.15.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Anime-Batle.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

Anime-Batle.app/Contents/PkgInfo: 
	@test -d Anime-Batle.app/Contents || mkdir -p Anime-Batle.app/Contents
	@$(DEL_FILE) Anime-Batle.app/Contents/PkgInfo
	@echo "APPL????" > Anime-Batle.app/Contents/PkgInfo
Anime-Batle.app/Contents/Resources/empty.lproj: 
	@test -d Anime-Batle.app/Contents/Resources || mkdir -p Anime-Batle.app/Contents/Resources
	@touch Anime-Batle.app/Contents/Resources/empty.lproj
	
Anime-Batle.app/Contents/Info.plist: 
	@test -d Anime-Batle.app/Contents || mkdir -p Anime-Batle.app/Contents
	@$(DEL_FILE) Anime-Batle.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Anime-Batle,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Anime-Batle,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Anime-Batle,g" -e "s,@LIBRARY@,Anime-Batle,g" -e "s,\$${EXECUTABLE_NAME},Anime-Batle,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../Qt/5.15.2/clang_64/mkspecs/macx-clang/Info.plist.app >Anime-Batle.app/Contents/Info.plist

all: Makefile \
		Anime-Batle.app/Contents/PkgInfo \
		Anime-Batle.app/Contents/Resources/empty.lproj \
		Anime-Batle.app/Contents/Info.plist Anime-Batle.app/Contents/MacOS/Anime-Batle

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents AnimeBattle.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents animebattle.h character_select.h param.h presets.h $(DISTDIR)/
	$(COPY_FILE) --parents character_select.cpp main.cpp animebattle.cpp param.cpp presets.cpp $(DISTDIR)/
	$(COPY_FILE) --parents animebattle.ui character_select.ui param.ui presets.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Anime-Batle.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_AnimeBattle.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_AnimeBattle.cpp
qrc_AnimeBattle.cpp: AnimeBattle.qrc \
		../Qt/5.15.2/clang_64/bin/rcc \
		static/Ico/ABLogo.ico \
		static/Preview/Kurama_preview.png \
		static/Preview/Milo_Preview.png \
		static/Preview/Gabimaru_preview.png \
		static/Preview/Goku_preview.png \
		static/Preview/Dio_preview.png \
		static/Preview/Ryo_Kaori_preview.png \
		static/BG/Kame_house.jpg \
		static/BG/Vallee_de_la_fin.png \
		static/BG/TitleBG.png \
		static/BG/Raimon.png \
		static/Music/Pegasus_Forever.mp3 \
		static/Music/Bioman.mp3 \
		static/Music/Sign.mp3 \
		static/Music/Overdrive.mp3 \
		static/Music/Tapion_Ocarina.mp3 \
		static/Music/Hyperdrive.mp3 \
		static/Music/Yusha_no_fue.mp3 \
		static/Music/River_in_the_desert.mp3 \
		static/Music/Passionate_duelist.mp3 \
		static/Music/Mass_Destruction.mp3 \
		static/Music/Wildfire.mp3 \
		static/Music/Struggle_of_sadness.mp3 \
		static/Music/Get_Wild.mp3 \
		static/Music/Pegasus_Fantasy.mp3 \
		static/Music/Kaidoku_Funou.mp3
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/rcc -name AnimeBattle AnimeBattle.qrc -o qrc_AnimeBattle.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_animebattle.cpp moc_character_select.cpp moc_param.cpp moc_presets.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_animebattle.cpp moc_character_select.cpp moc_param.cpp moc_presets.cpp
moc_animebattle.cpp: animebattle.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		moc_predefs.h \
		../Qt/5.15.2/clang_64/bin/moc
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/silarbinunzio/Anime-Batle/moc_predefs.h -I/Users/silarbinunzio/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/silarbinunzio/Anime-Batle -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib animebattle.h -o moc_animebattle.cpp

moc_character_select.cpp: character_select.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		moc_predefs.h \
		../Qt/5.15.2/clang_64/bin/moc
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/silarbinunzio/Anime-Batle/moc_predefs.h -I/Users/silarbinunzio/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/silarbinunzio/Anime-Batle -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib character_select.h -o moc_character_select.cpp

moc_param.cpp: param.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		moc_predefs.h \
		../Qt/5.15.2/clang_64/bin/moc
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/silarbinunzio/Anime-Batle/moc_predefs.h -I/Users/silarbinunzio/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/silarbinunzio/Anime-Batle -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib param.h -o moc_param.cpp

moc_presets.cpp: presets.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		moc_predefs.h \
		../Qt/5.15.2/clang_64/bin/moc
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/silarbinunzio/Anime-Batle/moc_predefs.h -I/Users/silarbinunzio/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/silarbinunzio/Anime-Batle -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/Users/silarbinunzio/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/silarbinunzio/Qt/5.15.2/clang_64/lib presets.h -o moc_presets.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_animebattle.h ui_character_select.h ui_param.h ui_presets.h
compiler_uic_clean:
	-$(DEL_FILE) ui_animebattle.h ui_character_select.h ui_param.h ui_presets.h
ui_animebattle.h: animebattle.ui \
		../Qt/5.15.2/clang_64/bin/uic
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/uic animebattle.ui -o ui_animebattle.h

ui_character_select.h: character_select.ui \
		../Qt/5.15.2/clang_64/bin/uic
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/uic character_select.ui -o ui_character_select.h

ui_param.h: param.ui \
		../Qt/5.15.2/clang_64/bin/uic
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/uic param.ui -o ui_param.h

ui_presets.h: presets.ui \
		../Qt/5.15.2/clang_64/bin/uic
	/Users/silarbinunzio/Qt/5.15.2/clang_64/bin/uic presets.ui -o ui_presets.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

character_select.o: character_select.cpp character_select.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_character_select.h \
		param.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		animebattle.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		presets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character_select.o character_select.cpp

main.o: main.cpp animebattle.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		param.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

animebattle.o: animebattle.cpp animebattle.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		ui_animebattle.h \
		param.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		character_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animebattle.o animebattle.cpp

param.o: param.cpp param.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../Qt/5.15.2/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		ui_param.h \
		animebattle.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o param.o param.cpp

presets.o: presets.cpp presets.h \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_presets.h \
		character_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o presets.o presets.cpp

qrc_AnimeBattle.o: qrc_AnimeBattle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_AnimeBattle.o qrc_AnimeBattle.cpp

moc_animebattle.o: moc_animebattle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animebattle.o moc_animebattle.cpp

moc_character_select.o: moc_character_select.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_character_select.o moc_character_select.cpp

moc_param.o: moc_param.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_param.o moc_param.cpp

moc_presets.o: moc_presets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_presets.o moc_presets.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Anime-Batle/bin || mkdir -p $(INSTALL_ROOT)/opt/Anime-Batle/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Anime-Batle/bin/Anime-Batle.app
	
	$(QINSTALL) Anime-Batle.app $(INSTALL_ROOT)/opt/Anime-Batle/bin/Anime-Batle.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Anime-Batle/bin/Anime-Batle.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Anime-Batle/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

